### ISSUE TITLE
Clarify language around "innovation"

### ISSUE THREAD

**Issue by adactio** [Podcast-Standards-Project/web-ui#1]
The website currently uses the word "innovation" twice:

1. > This is the landscape that has birthed The Podcast Standards Project, a grassroots coalition working to establish modern, open standards, to enable innovation in the podcast industry.
2. > PSP Certification recognizes companies that are prioritizing open podcasting by supporting innovative open podcast technology.

Please clarify what innovation means in this context.

Specifically, does "innovation" include the standardisation of the tracking and surveillance of people listening to podcasts? (The word "innovation" is often used to disguise practices that benefit companies at the expense of end users).

**Comment by geeknews** [comment]
The innovation is the expansion of RSS with new tags and features which is happening at a rapid pace.

Some companies in the podcasting space grew up respecting listener privacy including mine, and we have strict privacy rules, aka global adoption or GDPR and CCPA. My company at least does not allow the mining of IPs, and we anonymize that data after we process their stats.  If a creator chooses to employ a service that does re-targeting etc., that is their choice. We even warn podcasters using our service that they need to be aware of privacy policies for any company they use for measurement etc. 

Not every podcast company is out to monetize the audience, and we are well aware of those that do through various levels of data mining.

**Comment by snookfin** [comment]
Hey @adactio. I see the concern. Do you have any suggestions on how we can adjust the verbiage to capture the spirit of "innovation" without erroneously endorsing tracking and privacy violating behavior?

**Comment by RSSCOM** [comment]
That's a fair question; probably based in past experience. For example, [this article ](https://mignano.medium.com/the-standards-innovation-paradox-e14cab521391) calling for the destruction of RSS in the name of podcast innovation (ahem, and control) really flipped my lid. According to that author, collective innovation by disparate podcast groups is too hard and not fun (what a paradox!!!). The PSP is a disparate podcast industry grouping that doesn't think anything is too hard and in turn finds fun in the challenge of finding and assimilating podcast innovations on behalf of creators and listeners and collectively pushing them to wider adoption **within the confines of RSS** (because its currently the structure of podcast distribution, open, extensible, and somewhat privacy preserving).  I hope the word "innovation" hasn't been so severely tainted by others that's it's become impossible to use in its honest meaning.

**Comment by adactio** [comment]
@snookfin wrote:

> Hey @adactio. I see the concern. Do you have any suggestions on how we can adjust the verbiage to capture the spirit of "innovation" without erroneously endorsing tracking and privacy violating behavior?

Personally, I would replace the word "innovation" with something (anything) more specific. If there is nothing more specific to replace it with, then I would remove the word entirely.

Right now, it may well be doing more harm than good—ringing alarm bells instead of generating excitement.

@RSSCOM wrote:

>  I hope the word "innovation" hasn't been so severely tainted by others that's it's become impossible to use in its honest meaning.

Alas, that ship has long sailed.

**Comment by geeknews** [comment]
The simple fact is that we are innovating in a way that has not happened in RSS since 2005. I guess in my noncynical world; innovation is still a positive thing.  Yet if Spotify or Google used it, I would raise an eyebrow.

**Comment by snookfin** [comment]
1. > This is the landscape that has birthed The Podcast Standards Project, a grassroots coalition working to establish modern, open standards, to enable innovation in the podcast industry.

The word "innovation" here is a benefit statement. This is trying to quickly communicate why modern, open standards are good. The callout on the homepage says it a little differently...

How do we all feel about something like this?

> This is the landscape that has birthed The Podcast Standards Project, a grassroots industry coalition dedicated to creating standards and practices that improve the open podcasting ecosystem for both listeners and creators.

What I like about this is that it's specific about the audiences we're looking to serve.

As for #2 - the word "innovative" is simply an adjective. The sentence works fine without it; maybe better.
2. > PSP Certification recognizes companies that are prioritizing open podcasting by supporting open podcast technology.

**Comment by cameronmoll** [comment]
Appreciate the feedback @adactio. The following changes have been committed:

**HOME**

> This is the landscape that has birthed The Podcast Standards Project, a grassroots coalition working to establish modern, open standards, to enable innovation in the podcast industry.

Changed to:

> This is the landscape that has birthed The Podcast Standards Project, a grassroots coalition dedicated to creating standards and practices that improve the open podcasting ecosystem for both listeners and creators.

> PSP Certification recognizes companies that are prioritizing open podcasting by supporting innovative open podcast technology.

Changed to:

> PSP Certification recognizes companies that are prioritizing open podcasting technology.

**GET INVOLVED**

> PSP Certification recognizes companies that are prioritizing open podcasting by supporting innovative open podcast technology.

Changed to:

> PSP Certification recognizes companies that are prioritizing open podcasting technology.

**PROPOSALS**

> In an effort to establish modern, open standards that enable innovation in the podcast industry, we will pursue specific proposals through open collaboration.

Changed to:

> In an effort to establish standards and practices that improve the open podcasting ecosystem for both listeners and creators, we will pursue specific proposals through open collaboration.
