### ISSUE TITLE
Define what a podcast is

### ISSUE THREAD

**Issue by hellosteadman** [Podcast-Standards-Project/web-ui#3]
Is it worth creating a page on the website that defines what the word “podcast” means in the eyes of the standards body?

It might help those who have difficulty — or disinterest — in drawing lines between a podcast, an exclusive audio show, and a YouTube channel.

I’m thinking something that says, in effect, “you can call a podcast whatever you like. But when we use the word, this is what we mean”.

**Comment by snookfin** [comment]
It is worth defining what the PSP considers a podcast. We could add it to the proposals page. It probably doesn't need to be a stand-alone proposal; maybe just a clarifying statement that sits atop all of the proposals?

**Comment by cameronmoll** [comment]
+1 worth defining. Thinking out loud: "The Podcast Standards Project defines a 'podcast' as a live or recorded audio broadcast that may also be rendered as video, accessible by any listener from any web-enabled device capable of audio streaming or playback, irrespective of how or where the source file(s) is transmitted."

Not terribly convinced of my wording, but a first poke at it.

Here's what ChatGPT says: "A podcast is a digital audio program that can be downloaded or streamed over the internet ... [which] can be listened to on various devices, including smartphones, tablets, and computers, and can be accessed through various platforms, such as Apple Podcasts, Spotify, Google Podcasts, and others."

**Comment by cameronmoll** [comment]
Just realized both definitions above are missing an important component: RSS feed.

**Comment by snookfin** [comment]
This is from the very top of [PSP-1](https://github.com/Podcast-Standards-Project/PSP-1-Podcast-RSS-Specification/blob/main/0.9.md)

# What is a podcast?
The Podcast Standards Projects recognizes a podcast as downloadable audio and/or video content with an associated RSS feed.
